import unittest

from proteibb.core.source import properties
from proteibb.util.property import *

class PropertyTestCase(unittest.TestCase):

    def test_detailed_string_property(self):
        sp = properties.DetailedStringProperty('name')
        self.assertEqual(sp.get_name(), 'name')
        self.assertEqual(sp.get_value(), "")
        self.assertRaises(SyntaxError, sp.set_value, 12345)
        self.assertEqual(sp.set_value('string'), None)
        self.assertEqual(sp.get_value(), 'string')
        self.assertEqual(sp.is_optional(), True)
        self.assertEqual(sp.is_detail_specific(), True)

    def test_url_property(self):
        up = properties.UrlProperty()
        self.assertEqual(up.get_name(), 'url')
        self.assertEqual(up.get_value(), "")
        self.assertEqual(up.is_optional(), False)
        self.assertEqual(up.is_detail_specific(), False)
        self.assertRaises(SyntaxError, up.set_value, 12345)
        self.assertRaises(SyntaxError, up.set_value, '')
        self.assertRaises(SyntaxError, up.set_value, 'abcdef')
        self.assertRaises(SyntaxError, up.set_value, '://')
        self.assertRaises(SyntaxError, up.set_value, 'github.com/user/project')
        self.assertRaises(SyntaxError, up.set_value, 'http://hg.company\project\path')
        self.assertEqual(up.set_value('http://svn.server.com/db'), None)
        self.assertEqual(up.get_value(), 'http://svn.server.com/db')

    def test_vcs_property(self):
        vp = properties.VcsProperty()
        self.assertEqual(vp.get_name(), 'vcs')
        self.assertEqual(vp.get_value(), "")
        self.assertEqual(vp.is_optional(), False)
        self.assertEqual(vp.is_detail_specific(), False)
        self.assertRaises(SyntaxError, vp.set_value, 12345)
        self.assertRaises(SyntaxError, vp.set_value, '')
        self.assertRaises(SyntaxError, vp.set_value, 'svvn')
        self.assertRaises(SyntaxError, vp.set_value, 'mercurial')
        self.assertEqual(vp.set_value('svn'), None)
        self.assertEqual(vp.get_value(), 'svn')
        self.assertEqual(vp.set_value('git'), None)
        self.assertEqual(vp.get_value(), 'git')
        self.assertEqual(vp.set_value('hg'), None)
        self.assertEqual(vp.get_value(), 'hg')

    def test_version_property(self):
        vp = properties.VersionsProperty()
        self.assertEqual(vp.get_name(), 'versions')
        self.assertEqual(vp.get_value(), [])
        self.assertEqual(vp.is_optional(), True)
        self.assertEqual(vp.is_detail_specific(), True)
        self.assertRaises(SyntaxError, vp.set_value, 123456)
        self.assertRaises(SyntaxError, vp.set_value, 'abcd')
        self.assertRaises(SyntaxError, vp.set_value, [''])
        self.assertRaises(SyntaxError, vp.set_value, ['.'])
        self.assertRaises(SyntaxError, vp.set_value, ['.0.0'])
        self.assertRaises(SyntaxError, vp.set_value, ['4.'])
        self.assertRaises(SyntaxError, vp.set_value, ['a.b.c'])
        self.assertRaises(SyntaxError, vp.set_value, ['4.0.a'])
        self.assertRaises(SyntaxError, vp.set_value, ['1.2.3', '1.'])
        self.assertEqual(vp.set_value(['1.0.0']), None)
        self.assertEqual(vp.get_value(), [[1, 0, 0]])
        self.assertEqual(vp.set_value(['12']), None)
        self.assertEqual(vp.get_value(), [[12]])
        self.assertEqual(vp.set_value(['4.0', '5.2']), None)
        self.assertEqual(vp.get_value(), [[4, 0], [5, 2]])

    def test_dependencies_property(self):
        dp = properties.DependenciesProperty()
        self.assertEqual(dp.get_name(), 'dependencies')
        self.assertEqual(dp.get_value(), [])
        self.assertEqual(dp.is_optional(), True)
        self.assertEqual(dp.is_detail_specific(), True)
        self.assertRaises(SyntaxError, dp.set_value, 12345)
        self.assertRaises(SyntaxError, dp.set_value, '')
        self.assertRaises(SyntaxError, dp.set_value, [''])
        self.assertRaises(SyntaxError, dp.set_value, ['lib_a', ''])
        self.assertRaises(SyntaxError, dp.set_value, ['lib_a', 'lib_d:'])
        self.assertRaises(SyntaxError, dp.set_value, ['lib_a:1..0'])
        self.assertRaises(SyntaxError, dp.set_value, ['lib_a:1.0.0:'])
        self.assertRaises(SyntaxError, dp.set_value, ['lib_a', 'lib_d', 'lib_c:<<1000'])
        self.assertRaises(SyntaxError, dp.set_value, ['lib_a:>=1.0.0'])
        self.assertRaises(SyntaxError, dp.set_value, ['lib_a:>.0.0'])
        self.assertRaises(SyntaxError, dp.set_value, ['lib_a:4.0:4.'])
        self.assertRaises(SyntaxError, dp.set_value, ['lib_a:<>2.0'])
        self.assertRaises(SyntaxError, dp.set_value, ['lib_a:>1.0:>a'])
        self.assertRaises(SyntaxError, dp.set_value, ['lib_a>1.0.0'])
        self.assertRaises(SyntaxError, dp.set_value, ['lib_a3.1'])
        self.assertRaises(SyntaxError, dp.set_value, ['lib_a:>1.5.0:<1.2.5'])
        self.assertEqual(dp.set_value(['lib_a']), None)
        self.assertEqual(dp.get_value()[0].get_name(), 'lib_a')
        self.assertEqual(dp.get_value()[0].get_versions(), {'ver': [], 'min': None, 'max': None})
        self.assertEqual(dp.set_value(['lib_a:=1.0:=2.0']), None)
        self.assertEqual(dp.get_value()[0].get_name(), 'lib_a')
        self.assertEqual(dp.get_value()[0].get_versions(), {'ver': [[1, 0], [2, 0]], 'min': None, 'max': None})
        self.assertEqual(dp.set_value(['lib_b:>1.0:<2.0']), None)
        self.assertEqual(dp.get_value()[0].get_name(), 'lib_b')
        self.assertEqual(dp.get_value()[0].get_versions(), {'ver': [], 'min': [1, 0], 'max': [2, 0]})
        self.assertEqual(dp.set_value(['lib_c:=1.0:>2.0']), None)
        self.assertEqual(dp.get_value()[0].get_name(), 'lib_c')
        self.assertEqual(dp.get_value()[0].get_versions(), {'ver': [], 'min': [2, 0], 'max': None})
        self.assertEqual(dp.set_value(['lib_d:=2.0:>2.0']), None)
        self.assertEqual(dp.get_value()[0].get_name(), 'lib_d')
        self.assertEqual(dp.get_value()[0].get_versions(), {'ver': [[2, 0]], 'min': [2, 0], 'max': None})

    def test_string_list_property(self):
        slp = StringsListProperty('slp')
        self.assertEqual(slp.get_name(), 'slp')
        self.assertEqual(slp.is_optional(), False)
        self.assertRaises(SyntaxError, slp.set_value, '')
        self.assertRaises(SyntaxError, slp.set_value, 12345)
        self.assertRaises(SyntaxError, slp.set_value, [""])
        self.assertRaises(SyntaxError, slp.set_value, ['x86', ''])
        self.assertRaises(SyntaxError, slp.set_value, ['arm', 12345])
        self.assertEqual(slp.set_value(['x86', 'arm']), None)
        self.assertEqual(slp.get_value(), ['x86', 'arm'])

if __name__ == '__main__':
    unittest.main()
